site_name: "Documentación Invex ONE"  # Nombre del sitio de documentación
nav:
  - Home: index.md  # Página principal
  - Refresh Token API: refresh-token.md  # Documentación específica de la API
  - Solution Design: solutionDesign.md  # Documentación Solution Design

plugins:
  - techdocs-core  # Habilita el plugin TechDocs para integrar con Backstage

repo_url: https://github.com/LuisMalpica93/Backstage/tree/main/docs  # URL de tu repositorio en GitHub
edit_uri: https://github.com/LuisMalpica93/Backstage/edit/main/docs  # URL para editar los documentos directamente
