apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: CSCH-PTYA-SEC-PasswordRecoveryManagement
  description: |
    This contract is responsible for managing the password recovery process. It validates the user's identity and facilitates the secure retrieval of access credentials by sending a recovery link or code through the designated communication channel, such as email or SMS. The contract is based on BIAN version 11
  version: 1.0.0
spec:
  type: openapi
  lifecycle: experimental
  owner: party-authentication
  system: WSO2-API_MANAGER
  definition: |
    openapi: 3.0.1
    info:
      title: CSCH-PTYA-SEC-PasswordRecoveryManagement  
      description: This contract is responsible for managing the password recovery process. It validates the user's identity and facilitates the secure retrieval of access credentials by sending a recovery link or code through the designated communication channel, such as email or SMS. The contract is based on BIAN version 11
      
      version: 1.0.0
     
    servers:
      - url: wso2.apiman.invex
        description: Dev
        
    paths:
      '/api/v1/CrossChannel/PartyAuthentication/Password/passwordRecovery':
        post:
          tags:
            - BQ - Password Recovery
          summary: PrBQ  Initiate Password Recovery Process
          description: This endpoint allows users to initiate the password recovery process. It validates the user's identity and sends a recovery email with further instructions.  
          
          
          parameters:
          
            - $ref: '#/components/parameters/Authorization'
            - $ref: '#/components/parameters/Content-Type'
            - $ref: '#/components/parameters/Accept'
            - $ref: '#/components/parameters/Content-Length'
            - $ref: '#/components/parameters/User-Agent'
            - $ref: '#/components/parameters/Date'
            - $ref: '#/components/parameters/Channel-Id'
            - $ref: '#/components/parameters/X-brand-device'
            - $ref: '#/components/parameters/X-app-version'
            - $ref: '#/components/parameters/X-os-version'
            - $ref: '#/components/parameters/X-os'
            - $ref: '#/components/parameters/X-app-device-uid'
            - $ref: '#/components/parameters/X-tx-id'
            - $ref: '#/components/parameters/X-user-location'
            - $ref: '#/components/parameters/tnxv'
            
          requestBody:
    
            $ref: '#/components/requestBodies/PasswordRecoveryRequest' 
    
          responses:
            '200':
              description: Operation successful.
            '400':
              $ref: '#/components/responses/BadRequest'
            '401':
              $ref: '#/components/responses/Unauthorized'
            '403':
              $ref: '#/components/responses/Forbidden'
            '404':
              $ref: '#/components/responses/NotFound'
            '429':
              $ref: '#/components/responses/TooManyRequests'
            '500':
              $ref: '#/components/responses/InternalServerError'
              
      
      '/api/v1/CrossChannel/PartyAuthentication/Password/passwordUpdate':
        post:
          tags:
            - BQ - Password Update 
          summary: PuBQ Update User Password 
          description:  This endpoint allows authenticated users to update their password securely. The request must include the current password and the new password, ensuring compliance with security policies. The system validates the credentials and updates the password accordingly.
    
          parameters:
          
            - $ref: '#/components/parameters/Authorization'
            - $ref: '#/components/parameters/Content-Type'
            - $ref: '#/components/parameters/Accept'
            - $ref: '#/components/parameters/Content-Length'
            - $ref: '#/components/parameters/User-Agent'
            - $ref: '#/components/parameters/Date'
            - $ref: '#/components/parameters/Channel-Id'
            - $ref: '#/components/parameters/X-brand-device'
            - $ref: '#/components/parameters/X-app-version'
            - $ref: '#/components/parameters/X-os-version'
            - $ref: '#/components/parameters/X-os'
            - $ref: '#/components/parameters/X-app-device-uid'
            - $ref: '#/components/parameters/X-tx-id'
            - $ref: '#/components/parameters/X-user-location'
            - $ref: '#/components/parameters/tnxv'
                
          requestBody:
          
            $ref: '#/components/requestBodies/PasswordUpdateRequest'
            
          responses:
            '200':
              description: Operation successful.
            '400':
              $ref: '#/components/responses/BadRequest'
            '401':
              $ref: '#/components/responses/Unauthorized'
            '403':
              $ref: '#/components/responses/Forbidden'
            '404':
              $ref: '#/components/responses/NotFound'
            '429':
              $ref: '#/components/responses/TooManyRequests'
            '500':
              $ref: '#/components/responses/InternalServerError'
              
      
    components:
      schemas:
      
        HTTPError:
          type: object
          properties:
            type:
              type: string
              description: The type of the error (e.g., client error, server error).
              example: "Error"
            code:
              type: string
              description: A specific error code.
              example: "400"
            details:
              type: string
              description: Detailed information about the error.
              example: "Invalid request parameters"
            location:
              type: string
              description: The location where the error occurred (e.g., a URL or endpoint).
              example: "/api/v1/resource"
            traceId:
              type: string
              description: A unique identifier for the error, useful for troubleshooting.
              example: "f4d0a837-56b8-4baf-bbfe-9294a34331bc"
            timestamp:
              type: string
              format: date-time
              description: The timestamp when the error occurred.
              example: "2025-01-30T14:35:58Z"
          description: Schema representing an HTTP error response.
    
        PasswordRecoveryRequest:
          type: object
          properties:
            guide:
              type: object
              description: Contains the necessary information for the password recovery process.
              example:
                partyauthenticationid: "123456789"
              properties:
                partyauthenticationid:
                  type: string
                  description: Invex Now user identifier
                  example: "123456789"
                  
        PasswordUpdateRequest:
          type: object
          properties:
            passwordUpdate:
              type: object
              description: Contains the required information to update the user's password.
              properties:
                newPassword:
                  type: string
                  description: The new password chosen by the user.
                  example: "SecurePass123!"
                contextReference:
                  type: string
                  description: A reference identifier for the password update context.
                  example: "SESSION_ABC123"
                otp:
                  type: string
                  description: One-time password (OTP) for verification.
                  example: "123456"              
        
      responses:
      
        BadRequest:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        Unauthorized:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        Forbidden:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        NotFound:
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        TooManyRequests:
          description: TooManyRequests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        InternalServerError:
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
    
      parameters:
      
          Authorization:
            name: Authorization
            in: header
            schema:
             type: string
            description: Token de aplicación
            example: 77128ffa-6201-3c4a-939a-e5d0b2343b29
          
          Content-Type:
            name: Content-Type
            in: header
            schema:
             type: string
            description: Content-Type
            example: application/json
              
          Accept:    
              name: Accept
              in: header
              schema:
               type: string
              description: Accept
              example: application/json
          
          Content-Length:  
              name: Content-Length
              in: header
              schema: 
               type: integer
              description: Content-Length
              example: 142
              
          User-Agent:    
              name: User-Agent
              in: header
              schema: 
               type: integer
              description: Content-Length 
              example: 142546
              
          Date: 
              name: Date
              in: header
              schema: 
               type: string
               format: date
              description: Timestamp de la petición (dd/mm/yyyy hh:mm:ss)
              example: 15/01/2025 16:35:58
              
          Channel-Id:    
              name: channel-id
              in: header
              schema:
                type: string
              description: Constante ONE para la aplicación, se utiliza para la traza e identificación de la petición de origen.
              example: ONE
              
          X-brand-device:    
              name: X-brand-device
              in: header
              schema: 
               type: string
              description: Fabricante del dispositivo (Apple, Samsung, Google, Oppo, etc..)
              example: Samsung
              
          X-app-version:   
              name: X-app-version
              in: header
              schema: 
               type: number
               format: float
              description: Versión del aplicativo que se está ejecutando (1.0.0, 1.0.1, 2.0.0, etc…)
              example: 1.0.0
          
          X-app-device-model:    
              name: X-app-device-model
              in: header
              schema: 
               type: string
              description: Modelo del dispositivo (SM-900, iPhone 8, iPhone X, moto-g)
              example: SM-900
              
          X-os-version:
              name: X-os-version
              in: header
              schema: 
               type: number
               format: float
              description: Versión de sistema operativo (16.1, 15.0, 12, etc…)
              example: 16.1
              
          X-os:
              name: X-os
              in: header
              schema: 
               type: string
              description: Sistema operativo del dispositivo (android, ios, etc…)
              example: android
              
          X-app-device-uid:    
              name: X-app-device-uid
              in: header
              schema: 
               type: string
              description: Identificador del dispositivo (Android deviceId, iOS UDI, 34470f8cea3d33e9,  611975b5-5d14-f041-5ef8-b19b1f9a0d4f)
              example: 34470f8cea3d33e9
          
          X-tx-id:    
              name: X-tx-id
              in: header
              schema: 
               type: string
              description: ID de request, UUID random por sesión o pre-sesión.
              example: 07f48e1e-c942-4652-bd5b-27437561e5f1
              
          X-user-location:    
              name: X-user-location
              in: header
              schema: 
               type: string
              description: Se enviará una cadena cifrada en AES con el siguiente formato user|latitude|longitude
              example: B7doPjC3T-2tKujLRsuB8F69gyy02WfDg0GIbFIrPTU=
            
          tnxv:  
              name: tnxv
              in: header
              schema: 
               type: string
              description: (WAF/aplicación)
              
          X-session-id:    
              name: X-session-id
              in: header
              schema: 
               type: string
              description: SID de sesión entregado por el servicio de login
              example: 0debce55-f52c-4a59-a3cc-f7ccf522bf34  
          
          contextId:    
              name: contextId
              in: header
              schema: 
               type: string
              description: Es una identificador para obtener la llave de cifrada
              example: 3fa85f64-5717-4562-b3fc-2c963f66afa64       
      
      requestBodies:
       
        PasswordRecoveryRequest:
         description: The request body contains the necessary information to initiate the password recovery process for the Invex Now user. The system uses the provided user identifier to validate the request and proceed with the recovery process.
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/PasswordRecoveryRequest'
         required: true      
         
        PasswordUpdateRequest:
          description: The request body contains the necessary information for updating the user's password. It includes the new password chosen by the user, a context reference for the password update session, and a one-time password (OTP) for verification
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordUpdateRequest'
