apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: csch-pyta-refreshtoken
  description: This service provides a refresh token to obtain a new access token when the current one expires.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: deprecated
  owner: team-authentication
  definition: |
    openapi: 3.0.1
    info:
      title: CSCH-PYTA-RefreshToken
      description: This service provides a refresh token to obtain a new access token when the current one expires. The contract is based on BIAN version 11
      version: 1.0.0
    servers:
      - url: wso2.apiman.invex
        description: Dev
    paths:
      /api/v1/CrossChannel/PartyAuthentication/Update:
        post:
          summary: RqCR - Request a Customer’s Authentication Update
          description: This endpoint allows you to update or retrieve a new refresh token for the user
          parameters:
            - name: Authorization
              in: header
              schema:
                type: string
                description: Application token
                example: 77128ffa-6201-3c4a-939a-e5d0b2343b29
            - name: Content-Type
              in: header
              schema:
                type: string
                example: application/json
            - name: Accept
              in: header
              schema:
                type: string
                example: application/json
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TokenRequest'
          responses:
            '200':
              description: Successful authentication response
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/AuthTokenResponse'
            '400':
              $ref: '#/components/responses/BadRequest'
            '401':
              $ref: '#/components/responses/Unauthorized'
    components:
      schemas:
        TokenRequest:
          type: object
          properties:
            refreshToken:
              type: string
              description: The refresh token used to request a new access token.
        AuthToken:
          type: object
          properties:
            accessToken:
              type: string
              description: JWT access token for authentication
            refreshToken:
              type: string
              description: Refresh token to obtain a new access token
        AuthTokenResponse:
          type: object
          properties:
            authToken:
              $ref: "#/components/schemas/AuthToken"
      responses:
        BadRequest:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
        Unauthorized:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
