site_name: "Documentación de APIs"
nav:
  - Home: index.md
  - Refresh Token API: refresh-token.md
plugins:
  - techdocs-core
repo_url: "https://github.com/LuisMalpica93/Backstage"
edit_uri: "edit/main/docs/"
